name: Formatear y Ejecutar Pruebas

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  format_and_test:
    runs-on: ubuntu-latest

    steps:
    # Verificar el repositorio y hacer checkout de la rama
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref || github.ref }}

    # Restaurar caché de dependencias
    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-cache-

    # Configurar Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Instalar dependencias
    - name: Install dependencies
      run: npm install

    # Guardar caché de dependencias
    - name: Save npm cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}

    # Ejecutar el comando de formato
    - name: Format code
      run: npm run format

    # Configurar usuario de Git
    - name: Set up Git user
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    # Hacer commit de los cambios si los hay
    - name: Commit changes
      run: |
        git add .
        git commit -m "Formato de código aplicado por GitHub Action" || echo "No changes to commit"

    # Hacer push de los cambios
    - name: Push changes
      run: git push origin HEAD:${{ github.head_ref || github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Ejecutar el servicio de desarrollo en segundo plano y redirigir los logs a un archivo
    - name: Run dev service
      run: npm run dev > dev.log 2>&1 &
      continue-on-error: true

    # Esperar a que el servicio de desarrollo esté listo
    - name: Wait for dev service
      run: npx wait-on http://localhost:5173

    # Verificar los logs del servicio para asegurarse de que no haya errores
    - name: Check dev service logs
      run: |
        if grep -i "error" dev.log; then
          echo "Error found in dev service logs"
          exit 1
        fi

    # Ejecutar pruebas
    - name: Run tests
      run: npm run test