name: Formatear c칩digo al hacer merge en develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el c칩digo del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js (versi칩n 20 en este caso)
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Instalar las dependencias del proyecto
      - name: Instalar dependencias
        run: npm install

      # 4. Ejecutar el comando de formateo
      - name: Ejecutar formato
        run: npm run format

      # 5. Hacer commit de cambios si es necesario
      - name: Hacer commit de cambios si es necesario
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Aplicar formato autom치ticamente tras merge a develop" || echo "No hay cambios que commitear"

      # 6. Hacer push a la rama original
      - name: Hacer push de los cambios
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          if [ "$(git rev-parse --abbrev-ref HEAD)" = "HEAD" ]; then
            BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
            git push origin HEAD:$BRANCH_NAME
          else
            git push origin HEAD
